apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
replicas:
  - name: cardinal-be
    count: 2
images:
  - name: ghcr.io/sohappytoday/cardinal-be
    newTag: 8475c9e
