apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardinal-be
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cardinal-be
  template:
    metadata:
      labels:
        app: cardinal-be
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: cardinal-be
          image: ghcr.io/sohappytoday/cardinal-be:8475c9e
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/cardinal
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQLDialect
