apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      template:
        spec:
          imagePullSecrets:            
            - name: ghcr-secret
          containers:
            - name: web
              image: ghcr.io/sohappytoday/likelion14th-blog:2fa87f6
              ports:
            - containerPort: 8080  
